### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [jobcurtis/upton-sinclair_king-coal#1]
- [x] Typogrify makes a change to content.opf that should be accepted.
- [x] We use `<b>` for formatting, `<strong>` for extra emphasis (see [SEMoS 8.3.3](https://standardebooks.org/manual/1.7.0/single-page#8.3.3)), so the places where `<strong>` is being used should be `<b>`.
- [x] In the case of the sign in 1-1, it doesn't need either; when the entire block element (`<p>`, `<blockquote>`, whatever) has the same formatting (not counting emphasis), we generally prefer to use CSS to format it rather than adding markup to the text.
- [x] The lines in 1-12 is from a song ("…from his Harrigan song"), not verse; same for 2-21 ("…he chanted" and "And Hal sang again", and also they're lines from the song in 1-1 that's labeled as such); and for 2-24 ("We have that in our song!").
- [x] Likewise in 4-3, it's from the Marseillaise ("… to sing the Marseillaise…"), the French national anthem. (And the Marseillaise, as a song title, should be in quotes; see [8.2.11.3](https://standardebooks.org/manual/1.7.0/single-page#8.2.11.3).)
- [x] We use the z3998:article type for short stories and individual poem (i.e. the section types); blockquotes from publications aren't tagged, they're just a generic blockquote.
- [x] The French words that are tagged are all in M-W, so should not be italicized/tagged; see [8.2.9.4](https://standardebooks.org/manual/1.7.0/single-page#8.2.9.4).
- [x] We only use `<sub>` for actual subscripts; if different-sized text is needed, it should be handled in CSS. Also, that byline should be in its own `<p>`.
- [x] There's still a TODO comment in 2-8.
- [x] The "Note:" in the Afterword is formatted as small caps (`<b>`) in the scans.
- [x] Spelling is British (colour, favour, centre, etc.), so the 98b9d0d commit should be reverted.
- [x] Removing "THE END" isn't editorial (we usually get rid of it before the first commit), and I don't think italicizing the books qualifies either (033e053, d731704, c6c9220, 7151f70).
- [x] The introduction and afterword should be non-fiction.
- [x] There is an instance in 2-20 of a comma being outside a quote, `… of the G.F.C.’, that…`.
- [x] The fulltitle file-as does not include the subtitle; see the example in [9.4.2.4](https://standardebooks.org/manual/1.7.0/single-page#9.4.2.4).
- [x] The many paragraphs in the afterword quoting from the court case should be in blockquotes, one for "Round the shaft…" and another for all of the paragraphs starting with "The Federal troops…".
- [x] It's not required, but for future projects, consider putting the "standard" SE CSS first, followed by custom CSS. This makes things easier to find, and it also makes it clear what is "standard" CSS from book-specific CSS. It also ensures that the custom CSS overrides the standard, if by chance they are targeting the same things.

**Comment by jobcurtis** [comment]
Ok great @vr8hub I think I've resolved everything on that list.
